### ISSUE TITLE
文件包解压失败，修复后也有文件损坏

### ISSUE THREAD

**Issue by zyrzjyzxy** [chen2438/zstu-study#16]

**Comment by chen2438** [comment]
请具体说明是什么文件

**Comment by zyrzjyzxy** [comment]
下载完后，解压压缩包会提示文件压缩文件已损坏。
![Uploading 2023-11-13 13 25 58.png…]()

**Comment by chen2438** [comment]
你是在哪里下载的；
请直接clone整个仓库
<img width="437" alt="image" src="https://github.com/chen2438/zstu-study/assets/53367039/a2586cc5-f5f6-4e74-88f8-452be6d48518">

**Comment by zyrzjyzxy** [comment]
已解决，之前是download zip不行，现在clone可行。
