### ISSUE TITLE
科艺学院的课程能PR吗

### ISSUE THREAD

**Issue by lwpigking** [chen2438/zstu-study#63]
我是浙江理工大学科技与艺术学院的学生，我能将我们学校的课程资料PR上来吗？

**Comment by zyrzjyzxy** [comment]
欢迎PR

**Comment by zyrzjyzxy** [comment]
> 欢迎PR

可以PR到dev分支

**Comment by MoonShlne** [comment]
@lwpigking  你不是浙江工业职业技术学院的吗，怎么就浙大理工了

**Comment by lwpigking** [comment]
@MoonShlne 我是浙江工业职业技术学院的！！！

**Comment by chen2438** [comment]
其他学校的可以在根目录下单独建一个文件夹，文件夹名就是学校名
